import { useCallback, useEffect, useState } from 'react';
import { Award, ExternalLink, Flame, RefreshCw, ShieldCheck, Trophy } from 'lucide-react';
import { badges, profile, type Badge } from '../data/content';

const accentMap = {
  green: { ring: 'border-neon-green/40', text: 'text-neon-green', glow: 'hover:shadow-glow-green' },
  cyan: { ring: 'border-neon-cyan/40', text: 'text-neon-cyan', glow: 'hover:shadow-glow-cyan' },
  violet: { ring: 'border-neon-violet/40', text: 'text-neon-violet', glow: 'hover:shadow-glow-violet' },
  amber: { ring: 'border-neon-amber/40', text: 'text-neon-amber', glow: 'hover:shadow-[0_0_24px_rgba(251,191,36,0.35)]' },
  pink: { ring: 'border-neon-pink/40', text: 'text-neon-pink', glow: 'hover:shadow-[0_0_24px_rgba(244,114,182,0.35)]' },
};

function BadgeTile({ badge }: { badge: Badge }) {
  const accent = accentMap[badge.accent ?? 'cyan'];
  return (
    <a
      href={badge.href}
      target="_blank"
      rel="noopener noreferrer"
      aria-label={`${badge.name} - ${badge.issuer}`}
      className={`shrink-0 w-40 panel ${accent.ring} ${accent.glow} p-3 flex items-center gap-3 transition-all duration-300 hover:-translate-y-0.5`}
    >
      {badge.src ? (
        <img
          src={badge.src}
          alt={badge.name}
          className="h-12 w-12 object-contain shrink-0"
          loading="lazy"
        />
      ) : (
        <div className={`h-12 w-12 shrink-0 rounded-md border ${accent.ring} ${accent.text} bg-bg-soft flex items-center justify-center`}>
          <Award size={22} />
        </div>
      )}
      <div className="flex flex-col min-w-0">
        <span className={`font-mono text-[11px] font-semibold ${accent.text} truncate leading-tight`}>
          {badge.name}
        </span>
        <span className="font-mono text-[9px] text-ink-mute truncate">{badge.issuer}</span>
      </div>
    </a>
  );
}

function BadgesMarquee() {
  if (badges.length === 0) return null;
  const looped = [...badges, ...badges];

  return (
    <div className="panel scanline overflow-hidden">
      <div className="flex items-center justify-between px-4 py-2 border-b border-bg-border bg-bg-soft">
        <div className="flex items-center gap-2 font-mono text-[10px] text-ink-mute">
          <Trophy size={11} className="text-neon-amber" />
          <span>verified_credentials.live</span>
        </div>
        <span className="font-mono text-[9px] text-neon-green flex items-center gap-1">
          <span className="w-1.5 h-1.5 rounded-full bg-neon-green animate-pulse" /> synced
        </span>
      </div>

      <div
        className="relative overflow-hidden py-3 px-2"
        style={{
          maskImage: 'linear-gradient(90deg, transparent, black 6%, black 94%, transparent)',
          WebkitMaskImage: 'linear-gradient(90deg, transparent, black 6%, black 94%, transparent)',
        }}
      >
        <div className="flex gap-3 animate-[marquee_30s_linear_infinite] whitespace-nowrap w-max">
          {looped.map((b, i) => (
            <BadgeTile key={`${b.name}-${i}`} badge={b} />
          ))}
        </div>
      </div>
    </div>
  );
}

function formatAge(seconds: number): string {
  if (seconds < 45) return 'just updated';
  if (seconds < 60 * 60) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 60 * 60 * 24) return `${Math.floor(seconds / 3600)}h ago`;
  if (seconds < 60 * 60 * 24 * 30) return `${Math.floor(seconds / 86400)}d ago`;
  return 'over a month ago';
}

function TryHackMeWidget() {
  const username = profile.tryhackmeUsername;
  const streakUrl = profile.tryhackmeStreakUrl;

  // Cache-bust version + load state.
  // The official streak image at tryhackme-images.s3.amazonaws.com/streak/<user>.png
  // is regenerated by TryHackMe's server on their own internal schedule (observed
  // ~24-48h), not on demand. So we:
  //   (1) fire a no-cors GET to the share URL on the off-chance it nudges regen,
  //   (2) cache-bust the <img> to refetch whatever's currently on S3,
  //   (3) call /api/streak-meta to read the Last-Modified from S3 and show a
  //       "updated Xh ago" label so visitors know the upstream freshness.
  const [refreshKey, setRefreshKey] = useState(0);
  const [imageOk, setImageOk] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [ageSeconds, setAgeSeconds] = useState<number | null>(null);
  const [lastModified, setLastModified] = useState<string | null>(null);

  const fetchMeta = useCallback(async () => {
    try {
      const r = await fetch(`/api/streak-meta?user=${encodeURIComponent(username)}`, {
        cache: 'no-store',
      });
      if (!r.ok) return;
      const data = (await r.json()) as { ageSeconds?: number; ts?: string | null };
      if (typeof data.ageSeconds === 'number') {
        setAgeSeconds(data.ageSeconds);
        setLastModified(data.ts ?? null);
      }
    } catch {
      /* silently ignore - we just hide the timestamp on failure */
    }
  }, [username]);

  const refresh = useCallback(() => {
    setRefreshing(true);
    fetch(`https://tryhackme.com/${username}/streak`, {
      mode: 'no-cors',
      cache: 'no-store',
      credentials: 'omit',
      referrerPolicy: 'no-referrer',
    }).catch(() => {});
    window.setTimeout(() => {
      setRefreshKey(Date.now());
      setImageOk(true);
      setRefreshing(false);
      void fetchMeta();
    }, 1600);
  }, [username, fetchMeta]);

  useEffect(() => {
    refresh();
    const onFocus = () => refresh();
    window.addEventListener('focus', onFocus);
    return () => window.removeEventListener('focus', onFocus);
  }, [refresh]);

  // Bump the displayed "Xm ago" once a minute even if we don't refetch.
  useEffect(() => {
    if (!lastModified) return;
    const tick = () => {
      const s = Math.max(0, Math.floor((Date.now() - new Date(lastModified).getTime()) / 1000));
      setAgeSeconds(s);
    };
    tick();
    const id = window.setInterval(tick, 60_000);
    return () => window.clearInterval(id);
  }, [lastModified]);

  const streakImg = `https://tryhackme-images.s3.amazonaws.com/streak/${username}.png${refreshKey ? `?ts=${refreshKey}` : ''}`;
  const ageLabel = ageSeconds != null ? formatAge(ageSeconds) : null;
  const fullTs = lastModified ? new Date(lastModified).toLocaleString() : undefined;

  return (
    <div className="panel panel-hover block group overflow-hidden">
      <div className="flex items-center justify-between px-4 py-2 border-b border-bg-border bg-bg-soft">
        <div className="flex items-center gap-2 font-mono text-[10px] text-ink-mute">
          <Flame size={11} className="text-neon-red" />
          <span>tryhackme.streak · @{username}</span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={refresh}
            aria-label="Refresh streak"
            title="Refresh streak"
            disabled={refreshing}
            className="text-ink-mute hover:text-neon-cyan transition-colors disabled:opacity-50"
          >
            <RefreshCw size={11} className={refreshing ? 'animate-spin' : ''} />
          </button>
          <span
            className="font-mono text-[9px] text-neon-amber flex items-center gap-1"
            title={fullTs ? `Upstream image last regenerated: ${fullTs}` : undefined}
          >
            <ShieldCheck size={9} />
            {ageLabel ?? 'live'}
          </span>
        </div>
      </div>

      <a
        href={streakUrl}
        target="_blank"
        rel="noopener noreferrer"
        className="block"
      >
        {imageOk ? (
          <div className="bg-[#0a0e14] overflow-hidden">
            <img
              key={refreshKey}
              src={streakImg}
              alt={`${username} TryHackMe streak`}
              className="w-full h-auto block group-hover:scale-[1.02] transition-transform duration-500"
              onError={() => setImageOk(false)}
            />
          </div>
        ) : (
          <div className="p-4 flex items-center gap-4 bg-gradient-to-br from-[#0a0e14] via-[#10141d] to-[#0a0e14] min-h-[120px] relative overflow-hidden">
            <div className="absolute inset-0 opacity-30 [mask-image:radial-gradient(ellipse_at_center,black,transparent_70%)]">
              <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(239,68,68,0.25),transparent_50%)]" />
            </div>

            <div className="relative shrink-0 h-16 w-16 rounded-lg border border-neon-red/40 bg-neon-red/10 flex items-center justify-center group-hover:shadow-[0_0_24px_rgba(239,68,68,0.4)] transition-shadow">
              <Flame
                size={32}
                className="text-neon-red drop-shadow-[0_0_8px_rgba(239,68,68,0.7)] group-hover:scale-110 transition-transform"
              />
            </div>

            <div className="relative flex-1 min-w-0">
              <div className="flex items-baseline gap-2">
                <span className="font-mono text-xl font-bold text-neon-red leading-none">live</span>
                <span className="font-mono text-[10px] text-ink-mute uppercase tracking-wider">
                  day streak
                </span>
              </div>
              <div className="mt-1 font-mono text-[11px] text-ink-dim">@{username}</div>
              <div className="mt-2 inline-flex items-center gap-1 font-mono text-[10px] text-neon-cyan group-hover:gap-2 transition-all">
                view current streak <ExternalLink size={10} />
              </div>
            </div>
          </div>
        )}
      </a>
    </div>
  );
}

export function BadgesStrip() {
  return (
    <div className="flex flex-col gap-3">
      <BadgesMarquee />
      <TryHackMeWidget />
    </div>
  );
}
