import { useState } from 'react';
import { Award, ExternalLink, Flame, ShieldCheck, Trophy } from 'lucide-react';
import { badges, profile, type Badge } from '../data/content';

const accentMap = {
  green: { ring: 'border-neon-green/40', text: 'text-neon-green', glow: 'hover:shadow-glow-green' },
  cyan: { ring: 'border-neon-cyan/40', text: 'text-neon-cyan', glow: 'hover:shadow-glow-cyan' },
  violet: { ring: 'border-neon-violet/40', text: 'text-neon-violet', glow: 'hover:shadow-glow-violet' },
  amber: { ring: 'border-neon-amber/40', text: 'text-neon-amber', glow: 'hover:shadow-[0_0_24px_rgba(251,191,36,0.35)]' },
  pink: { ring: 'border-neon-pink/40', text: 'text-neon-pink', glow: 'hover:shadow-[0_0_24px_rgba(244,114,182,0.35)]' },
};

function BadgeTile({ badge }: { badge: Badge }) {
  const accent = accentMap[badge.accent ?? 'cyan'];
  return (
    <a
      href={badge.href}
      target="_blank"
      rel="noopener noreferrer"
      aria-label={`${badge.name} - ${badge.issuer}`}
      className={`shrink-0 w-40 panel ${accent.ring} ${accent.glow} p-3 flex items-center gap-3 transition-all duration-300 hover:-translate-y-0.5`}
    >
      {badge.src ? (
        <img
          src={badge.src}
          alt={badge.name}
          className="h-12 w-12 object-contain shrink-0"
          loading="lazy"
        />
      ) : (
        <div className={`h-12 w-12 shrink-0 rounded-md border ${accent.ring} ${accent.text} bg-bg-soft flex items-center justify-center`}>
          <Award size={22} />
        </div>
      )}
      <div className="flex flex-col min-w-0">
        <span className={`font-mono text-[11px] font-semibold ${accent.text} truncate leading-tight`}>
          {badge.name}
        </span>
        <span className="font-mono text-[9px] text-ink-mute truncate">{badge.issuer}</span>
      </div>
    </a>
  );
}

function BadgesMarquee() {
  if (badges.length === 0) return null;
  const looped = [...badges, ...badges];

  return (
    <div className="panel scanline overflow-hidden">
      <div className="flex items-center justify-between px-4 py-2 border-b border-bg-border bg-bg-soft">
        <div className="flex items-center gap-2 font-mono text-[10px] text-ink-mute">
          <Trophy size={11} className="text-neon-amber" />
          <span>verified_credentials.live</span>
        </div>
        <span className="font-mono text-[9px] text-neon-green flex items-center gap-1">
          <span className="w-1.5 h-1.5 rounded-full bg-neon-green animate-pulse" /> synced
        </span>
      </div>

      <div
        className="relative overflow-hidden py-3 px-2"
        style={{
          maskImage: 'linear-gradient(90deg, transparent, black 6%, black 94%, transparent)',
          WebkitMaskImage: 'linear-gradient(90deg, transparent, black 6%, black 94%, transparent)',
        }}
      >
        <div className="flex gap-3 animate-[marquee_30s_linear_infinite] whitespace-nowrap w-max">
          {looped.map((b, i) => (
            <BadgeTile key={`${b.name}-${i}`} badge={b} />
          ))}
        </div>
      </div>
    </div>
  );
}

function TryHackMeWidget() {
  const username = profile.tryhackmeUsername;
  const streakUrl = profile.tryhackmeStreakUrl;
  // Official TryHackMe streak share image - generated by THM when streak > 0.
  // Returns 403 until then; we fall back to a custom card via onError.
  const streakImg = `https://tryhackme-images.s3.amazonaws.com/streak/${username}.png`;
  const [imageOk, setImageOk] = useState(true);

  return (
    <a
      href={streakUrl}
      target="_blank"
      rel="noopener noreferrer"
      className="panel panel-hover block group overflow-hidden"
    >
      <div className="flex items-center justify-between px-4 py-2 border-b border-bg-border bg-bg-soft">
        <div className="flex items-center gap-2 font-mono text-[10px] text-ink-mute">
          <Flame size={11} className="text-neon-red" />
          <span>tryhackme.streak · @{username}</span>
        </div>
        <span className="font-mono text-[9px] text-neon-amber flex items-center gap-1">
          <ShieldCheck size={9} /> live
        </span>
      </div>

      {imageOk ? (
        <div className="bg-[#0a0e14] overflow-hidden">
          <img
            src={streakImg}
            alt={`${username} TryHackMe streak`}
            className="w-full h-auto block group-hover:scale-[1.02] transition-transform duration-500"
            loading="lazy"
            onError={() => setImageOk(false)}
          />
        </div>
      ) : (
        <div className="p-4 flex items-center gap-4 bg-gradient-to-br from-[#0a0e14] via-[#10141d] to-[#0a0e14] min-h-[120px] relative overflow-hidden">
          <div className="absolute inset-0 opacity-30 [mask-image:radial-gradient(ellipse_at_center,black,transparent_70%)]">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(239,68,68,0.25),transparent_50%)]" />
          </div>

          <div className="relative shrink-0 h-16 w-16 rounded-lg border border-neon-red/40 bg-neon-red/10 flex items-center justify-center group-hover:shadow-[0_0_24px_rgba(239,68,68,0.4)] transition-shadow">
            <Flame
              size={32}
              className="text-neon-red drop-shadow-[0_0_8px_rgba(239,68,68,0.7)] group-hover:scale-110 transition-transform"
            />
          </div>

          <div className="relative flex-1 min-w-0">
            <div className="flex items-baseline gap-2">
              <span className="font-mono text-xl font-bold text-neon-red leading-none">live</span>
              <span className="font-mono text-[10px] text-ink-mute uppercase tracking-wider">
                day streak
              </span>
            </div>
            <div className="mt-1 font-mono text-[11px] text-ink-dim">@{username}</div>
            <div className="mt-2 inline-flex items-center gap-1 font-mono text-[10px] text-neon-cyan group-hover:gap-2 transition-all">
              view current streak <ExternalLink size={10} />
            </div>
          </div>
        </div>
      )}
    </a>
  );
}

export function BadgesStrip() {
  return (
    <div className="flex flex-col gap-3">
      <BadgesMarquee />
      <TryHackMeWidget />
    </div>
  );
}
